version: "3.5"

services:
  app:
    build: .
    # entrypoint: dockerize -wait tcp://db:5432 -timeout 40s ./.docker/entrypoint.sh
    entrypoint: ./.docker/entrypoint.sh
    container_name: api-node
    ports:
      - 4000:3000
    volumes:
      - .:/home/node/app
    # depends_on:
    #   - db
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  # db:
  #   image: mongo:5.0.3
  #   restart: always
  #   ports:
  #   - 27017:27017
  #   volumes:
  #     - ./.docker/dbdata:/data/db
  #     - ./.docker/mongo:/docker-entrypoint-initdb.d
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=root
  #     - MONGO_INITDB_DATABASE=login
  #   networks:
  #     - app-network
  
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=db
  #     - ME_CONFIG_MONGODB_AUTH_USERNAME=root
  #     - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=root
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=root
  #   depends_on:
  #     - db
  #   networks:
  #     - app-network
  #   extra_hosts:
  #     - "host.docker.internal:172.17.0.1"

networks:
  app-network:
    driver: bridge
